from services.registration import registrate_user
from services.authorization import authorizate_user
from services.get_all_posts import get_all_posts
from services.get_all_users import get_all_users
from services.create import create
from services.get_post_from_post import get_post_post
from services.get_user_from_post import get_user_post
from services.get_post_innerjoin import posts_innerjoin
from services.comment import to_comment
from services.get_all_comments import get_all_comments
from services.get_comments import main_comments
from services.add_raite import raite_add
from services.luchsh import luchsh
